### ISSUE TITLE
WoW Client goes "Not responding" randomly with Quick DKP v2 addon

### ISSUE THREAD

**Issue by radieuse** [ElvUI-WotLK/ElvUI#521]
**Description**
My client randomly crashes whenever I have QDKP2 addon turned on with ElvUI. It doesn't crash when I disable ElvUI. I can't send you a log since I only get "Program not responding" from Windows 10.

**Version Number**
ElvUI Version: 5.41

**Steps to Reproduce**
1. Step 1: Enable Quick DKP v2 addon.
2. Step 2: Log in game.
3. Step 3: After 5-15minutes the client crashes.

**Expected Behavior**
Wow client not crashing with QDKP2 addon and ElvUI turned on.

**Actual Behavior**
Wow client crashing with QDKP2 and ElvUI turned on

**Only ElvUI Enabled**
Yes, I've tried testing for each and single one of my addons and only ElvUI makes my game crash with QDKP2 turned on.

**Blizzard Issue?**
No I can't, wow client doesn't crash after extensive gameplay (5-6 hours in game)

**Additional Information**
This has been an issue ever since I've been playing with ElvUI (around version 5.31 I believe).

**Error Log**
My problem is that I don't recieve an error log. So I can't provide you this information.

**Comment by Arsan11** [comment]
Can confirm this error happens to me as well. It didn't happen when i had standard QDKP addon but when i got promoted to officer and got the officer version of the addon it started to crash

**Comment by Trixarian** [comment]
http://trixarian.net/wow/ - try one of these two versions. 2.6.7 is the one you commonly find with the interface from 2.7.2 for easy configuration, while 2.7.5 is a full port from the Cata version to WoTLK. Both have been configured to not automatically hand out DKP by default and I fixed the ton of UI errors (check Logs\FrameXML.log in your game folder) that QDKP generates. The combination seems to fix the crashes for the most part, if it doesn't completely eliminate them

**Comment by skylarjm** [comment]
I've tested version 2.6.7 and it keeps crashing. But when you delete QDKP2_Config it works fine without any crashes.

**Comment by Trixarian** [comment]
Yeah, it's a collection of issues. I think the Guild data text of ElvUI and the guild check that QDKP2 does is conflicting with each other - especially when awarding points automatically. On ElvUI side, QDKP2 does /not/ like it taking control of the Loot and Loot Roll frames - so I suggest turning those off in ElvUI's config. As for 2.6.7 - it runs without crashing if QDKP2_Config isn't loaded - My guess as to why, is because it's using the interface from 2.7.2 and it's not completely compatible with 2.6.7 and comes with the Loot and Loot Roll frame bug (which isn't a problem with 2.6.7 since it was only introduced with the Cata versions or 2.7.x and up). That said, you don't have to delete QDKP2_Config, you just have to unload it - the easiest way is to use Addon Control Panel since it allows you to load and unload addons while ingame

**Comment by Arsan11** [comment]
Thank you for your comments!

**Comment by Orthrin** [comment]
I have a similar problem I deleted QDKP2 but the problem still exists any other problematic addons?

**Comment by Loaal** [comment]
A possible source of the problem was found and fixed.

**Comment by ArsumPB** [comment]
Will try to test today @Loaal

**Comment by ArsumPB** [comment]
Close it, doesn't crash anymore

**Comment by decadent83** [comment]
this addon is giving me stutters fps drops every 3-5 second, if addon is not enabled it runs perfect. So I need this addon to raid with my guild, but now its ruining my hole gaming experience. Anyone with the same problem? please help 🥇

**Comment by Barsoomx** [comment]
Disable qdkpv2-gui

**Comment by decadent83** [comment]
Thanks for your reply, I tried it and still fps drop happens :(

**Comment by Barsoomx** [comment]
If completely disabling QDKP helps, try clearing addon data and/or removing/replacing acetimer library with elvui one. Also, send me an addon archive so i can try it too

**Comment by decadent83** [comment]
I added my addons in a winrar, I hope the link and account works so you can download, let me know :)
[https://drive.google.com/file/d/1aNkhhCnyxoJ0KJPrtFcGaVnDwx4-UcjE/view?usp=sharing](url)

**Comment by Barsoomx** [comment]
Are you playing on retail classic? This is elvui-wotlk backport for WoTLK 3.3.5

**Comment by decadent83** [comment]
Im playing on wow classic yeah, oh, i downloaded on curseforge its the only quickdkp v2 i can find. It said it was the newest version for wow classic. Is there another version i can download somewhere else?

**Comment by Barsoomx** [comment]
I mean this elvui is not for classic, ask your questions in official tukui classic https://git.tukui.org/elvui/elvui-classic , we can't help you here sadly

**Comment by decadent83** [comment]
ah, I see. I will try there. Thank you for your time and help.
